#!/usr/bin/env bash

if test -t 1; then
    ncolors=$(tput colors)

    if test -n "$ncolors" && test "$ncolors" -ge 8; then
        BOLD="$(tput bold)"
        YELLOW="$(tput setaf 3)"
        GREEN="$(tput setaf 2)"
        RED="$(tput setaf 1)"
        NC="$(tput sgr0)"
    fi
fi

function __run() #(step, name, cmd)
{
    local color output exitcode

    printf "${YELLOW}[%s]${NC} %-20s" "$1" "$2"
    output=$(eval "$3" 2>&1)
    exitcode=$?

    if [[ 0 == $exitcode || 130 == $exitcode ]]; then
        echo -e "${GREEN}OK!${NC}"
    else
        echo -e "${RED}NOK!${NC}\n\n$output"
        exit 1
    fi
}

modified="git diff --diff-filter=M --name-only --cached  | grep \".php$\""
pint="vendor/bin/pint"
phpstan="vendor/bin/phpstan analyse"
pest="vendor/bin/pest"

if [ -n "$modified" ]; then
    __run "1/4" "php lint" "${modified} | xargs -r php -l"
    __run "2/4" "code sniffer" "${modified} | xargs -r ${pint}"
    __run "3/4" "phpstan" "${modified} | xargs -r ${phpstan}"
    __run "4/4" "tests" "${pest}"
fi
