name: Update Composer dependencies

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_ACTIONS_TOKEN }}

      - name: Install dependencies
        run: composer install

      - name: Update dependencies
        run: composer update

      - name: Bump dependencies
        run: composer bump

      - name: Update dependencies
        run: composer update

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add composer.lock
          git add composer.json
          git commit -m "Update/Bump composer dependencies"
          git push
